version: "3.8"

services:
  postgres:
    image: postgres:16.1
    container_name: task-mgmt-db
    environment:
      - POSTGRES_DB=task-mgmt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=erev0s13!
    ports:
      - 5432:5432
